# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - darwin
    - windows
    - linux
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  goarm:
    - 6
    - 7
  ignore:
    - goos: darawn
      goarch: arm
    - goos: darwin
      goarch: arm64
    - goos: windows
      goarch: arm
    - goos: windows
      goarch: arm64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
  files:
    - none*
  format: gz
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'